### ISSUE TITLE
lesson2 reflections

### ISSUE THREAD

**Issue by gytdev** [spacecadet84/reflections#1]
Hey fellow Udacian. Just stopping by to mention that I've read Your reflections2 and I really enjoy that You answer the questions in length. Do I sense a writers gene floating somewhere in You?

One thought about the first question:
Initializing a directory not just gets the ball rolling, but also creates a .git directory(hidden) at the directory in which You initialize. Git stores all the required files and commit history in the .git directory.

Big ups. And good luck with Your studies.

PS. Nice github name! :)

**Comment by spacecadet84** [comment]
Great to hear from another Udacian!  Thanks for the feedback on reflections.  I'm still a newb and I tend to get overly verbose when I'm confused I think.

Your explanation on initializing a directory was really helpful!  I just added that to the reflection.  Thanks again for reaching out and good luck to you as well!
